source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SuperMock_Example', :exclusive => true do
  pod "SuperMock", :path => "../"
end

target 'SuperMock_Tests', :exclusive => true do
  pod "SuperMock", :path => "../"
end
